---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/home
  label: Home
  create: documents
  match: "**/*"
  templates:
  - pages-widget
  - contact-widget
  - workshops-widget
  - hero-widget
  - gallery-widget
  - about-widget
  - home-page
- type: directory
  path: content/blog
  label: Blog posts
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: content/gallery
  label: Sculptures
  create: all
  match: "**/*"
  templates:
  - sculpture
- type: directory
  path: content/workshops
  label: Workshops
  create: all
  match: "**/*"
  templates:
  - workshop
- type: directory
  path: content/about-me
  label: About me
  create: all
  match: "**/*"
  templates:
  - page
  - about-me
- type: directory
  path: content/schools
  label: Schools
  create: all
  match: "**/*"
  templates:
  - page
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
